# tile_variation.py

from enum import Enum

class TileVariation(Enum):
    SOLID = 0
    EDGE_TOP = 1
    EDGE_BOTTOM = 2
    EDGE_LEFT = 3
    EDGE_RIGHT = 4
    CORNER_INNER_TOP_LEFT = 5
    CORNER_INNER_TOP_RIGHT = 6
    CORNER_INNER_BOTTOM_LEFT = 7
    CORNER_INNER_BOTTOM_RIGHT = 8
    CORNER_OUTER_TOP_LEFT = 9
    CORNER_OUTER_TOP_RIGHT = 10
    CORNER_OUTER_BOTTOM_LEFT = 11
    CORNER_OUTER_BOTTOM_RIGHT = 12
    DIAGONAL_TOP_LEFT_BOTTOM_RIGHT = 13
    DIAGONAL_TOP_RIGHT_BOTTOM_LEFT = 14
